easyflow.process.admin.page.processUnitExecutionDetail.excutionDetailInfo=Execution detail info
easyflow.process.admin.page.processUnitExecutionDetail.executionNo=Execution no
easyflow.process.admin.page.processUnitExecutionDetail.requestNo=Request no
easyflow.process.admin.page.processUnitExecutionDetail.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionDetail.bizNo=Biz no
easyflow.process.admin.page.processUnitExecutionDetail.productCode=Product code
easyflow.process.admin.page.processUnitExecutionDetail.result=Result
easyflow.process.admin.page.processUnitExecutionDetail.resultSuccess=Success
easyflow.process.admin.page.processUnitExecutionDetail.resultFail=Fail
easyflow.process.admin.page.processUnitExecutionDetail.resultDoing=Doing
easyflow.process.admin.page.processUnitExecutionDetail.resultException=Exception
easyflow.process.admin.page.processUnitExecutionDetail.execType=Exec type
easyflow.process.admin.page.processUnitExecutionDetail.execTypeSync=Sync
easyflow.process.admin.page.processUnitExecutionDetail.execTypeManual=Manual
easyflow.process.admin.page.processUnitExecutionDetail.execTypeTask=Task
easyflow.process.admin.page.processUnitExecutionDetail.execTypeMsg=Message
easyflow.process.admin.page.processUnitExecutionDetail.elapseTime=Elaspe time
easyflow.process.admin.page.processUnitExecutionDetail.requestTime=Request time
easyflow.process.admin.page.processUnitExecutionDetail.responseTime=Response time
easyflow.process.admin.page.processUnitExecutionDetail.createdDate=Created date
easyflow.process.admin.page.processUnitExecutionDetail.modifiedDate=Modified date
easyflow.process.admin.page.processUnitExecutionDetail.requestContent=Request content
easyflow.process.admin.page.processUnitExecutionDetail.responseContent=Response content
easyflow.process.admin.page.processUnitExecutionDetail.extData=Ext data

easyflow.process.admin.page.processUnitInstanceDetail.instanceDetailInfo=Instance detail info
easyflow.process.admin.page.processUnitInstanceDetail.instanceNo=Instance no
easyflow.process.admin.page.processUnitInstanceDetail.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitInstanceDetail.bizNo=Biz no
easyflow.process.admin.page.processUnitInstanceDetail.productCode=Product code
easyflow.process.admin.page.processUnitInstanceDetail.result=Result
easyflow.process.admin.page.processUnitInstanceDetail.resultSuccess=Success
easyflow.process.admin.page.processUnitInstanceDetail.resultFail=Fail
easyflow.process.admin.page.processUnitInstanceDetail.resultDoing=Doing
easyflow.process.admin.page.processUnitInstanceDetail.resultException=Exception
easyflow.process.admin.page.processUnitInstanceDetail.autoRunTimes=Auto run times
easyflow.process.admin.page.processUnitInstanceDetail.autoRunFlag=Auto run flag
easyflow.process.admin.page.processUnitInstanceDetail.nextAutoRunTime=Next auto run time
easyflow.process.admin.page.processUnitInstanceDetail.createdDate=Created date
easyflow.process.admin.page.processUnitInstanceDetail.modifiedDate=Modified date
easyflow.process.admin.page.processUnitInstanceDetail.requestContent=Request content
easyflow.process.admin.page.processUnitInstanceDetail.responseContent=Response content
easyflow.process.admin.page.processUnitInstanceDetail.vars=Variables
easyflow.process.admin.page.processUnitInstanceDetail.extData=Ext data
easyflow.process.admin.page.processUnitInstanceDetail.instanceShardInfo=Instance shard info
easyflow.process.admin.page.processUnitInstanceDetail.shard=Shard
easyflow.process.admin.page.processUnitInstanceDetail.db=Db
easyflow.process.admin.page.processUnitInstanceDetail.table=Table 
easyflow.process.admin.page.processUnitInstanceDetail.slaveShard=Slave shard
easyflow.process.admin.page.processUnitInstanceDetail.slaveDb=Slave db
easyflow.process.admin.page.processUnitInstanceDetail.slaveTable=Slave table
easyflow.process.admin.page.processUnitInstanceDetail.executionNo=Execution no
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestNo=Request no
easyflow.process.admin.page.processUnitInstanceDetail.executionResult=Result
easyflow.process.admin.page.processUnitInstanceDetail.executionResultSuccess=Success
easyflow.process.admin.page.processUnitInstanceDetail.executionResultFail=Fail
easyflow.process.admin.page.processUnitInstanceDetail.executionResultDoing=Doing
easyflow.process.admin.page.processUnitInstanceDetail.executionResultException=Exception
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestContent=Request content
easyflow.process.admin.page.processUnitInstanceDetail.executionResponseContent=Response content
easyflow.process.admin.page.processUnitInstanceDetail.executionExecType=Exec type
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeSync=Sync
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeManual=Manual
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeTask=Task
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeMsg=Message
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestTime=Request time
easyflow.process.admin.page.processUnitInstanceDetail.executionResponseTime=Response time
easyflow.process.admin.page.processUnitInstanceDetail.executionElapseTime=Elapse time
easyflow.process.admin.page.processUnitInstanceDetail.executionExtData=Ext data


easyflow.process.admin.page.processUnitExecutionList.executionManagement=Execution management
easyflow.process.admin.page.processUnitExecutionList.queryType=Query type
easyflow.process.admin.page.processUnitExecutionList.queryByInstance=Query by instance
easyflow.process.admin.page.processUnitExecutionList.queryByInstanceTip=Input instanceNo or unitCode+bizNo
easyflow.process.admin.page.processUnitExecutionList.queryByTime=Query by time range
easyflow.process.admin.page.processUnitExecutionList.queryByTimeTip=Input unitCode, time range and other
easyflow.process.admin.page.processUnitExecutionList.onlyFirstPageSupport=Only support first page
easyflow.process.admin.page.processUnitExecutionList.queryProcessUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionList.querySelect=Select
easyflow.process.admin.page.processUnitExecutionList.queryBizNo=Biz no
easyflow.process.admin.page.processUnitExecutionList.queryInstanceNo=Instance no
easyflow.process.admin.page.processUnitExecutionList.queryResult=Result
easyflow.process.admin.page.processUnitExecutionList.queryResultSuccess=Success
easyflow.process.admin.page.processUnitExecutionList.queryResultFail=Fail
easyflow.process.admin.page.processUnitExecutionList.queryResultDoing=Doing
easyflow.process.admin.page.processUnitExecutionList.queryResultException=Exception
easyflow.process.admin.page.processUnitExecutionList.queryRequestTimeStart=Request time start
easyflow.process.admin.page.processUnitExecutionList.queryRequestTimeEnd=Request time end
easyflow.process.admin.page.processUnitExecutionList.queryElapseTimeStart=Elapse time start
easyflow.process.admin.page.processUnitExecutionList.queryElapseTimeEnd=Elapse time end
easyflow.process.admin.page.processUnitExecutionList.queryBtn=Query
easyflow.process.admin.page.processUnitExecutionList.executionList=Execution list
easyflow.process.admin.page.processUnitExecutionList.dateFormatInvalid=Date format invalid
easyflow.process.admin.page.processUnitExecutionList.instanceInfoCannotNull=InstanceNo or unitCode+bizNo cannot null
easyflow.process.admin.page.processUnitExecutionList.processUnitCodeCannotNull=process unit code cannot null
easyflow.process.admin.page.processUnitExecutionList.timeRangeCannotNull=Start time and end time cannot null
easyflow.process.admin.page.processUnitExecutionList.startTimeCannotGtEndTime=Start time cannot greater than end time
easyflow.process.admin.page.processUnitExecutionList.TimeRangeCannotGt30Days=Time range cannot greater than 30 days
easyflow.process.admin.page.processUnitExecutionList.executionNo=Execution no
easyflow.process.admin.page.processUnitExecutionList.requestNo=Request no
easyflow.process.admin.page.processUnitExecutionList.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionList.bizNo=Biz no
easyflow.process.admin.page.processUnitExecutionList.result=Result
easyflow.process.admin.page.processUnitExecutionList.resultSuccess=Success
easyflow.process.admin.page.processUnitExecutionList.resultFail=Fail
easyflow.process.admin.page.processUnitExecutionList.resultDoing=Doing
easyflow.process.admin.page.processUnitExecutionList.resultException=Exception
easyflow.process.admin.page.processUnitExecutionList.requestContent=Request content
easyflow.process.admin.page.processUnitExecutionList.responseContent=Response content
easyflow.process.admin.page.processUnitExecutionList.execType=Exec type
easyflow.process.admin.page.processUnitExecutionList.requestTime=Request time
easyflow.process.admin.page.processUnitExecutionList.responseTime=Response time
easyflow.process.admin.page.processUnitExecutionList.elapseTime=Elapse time
easyflow.process.admin.page.processUnitExecutionList.extData=Ext date
easyflow.process.admin.page.processUnitExecutionList.createdDate=Created date
easyflow.process.admin.page.processUnitExecutionList.modifiedDate=Modified date
easyflow.process.admin.page.processUnitExecutionList.nextPage=Next page

easyflow.process.admin.page.processUnitInstanceList.instanceManagement=Instance management
easyflow.process.admin.page.processUnitInstanceList.queryByInstance=query by instance
easyflow.process.admin.page.processUnitInstanceList.queryByInstanceTip=Input instanceNo or bizNo+unitCode
easyflow.process.admin.page.processUnitInstanceList.queryByTime=query by time range
easyflow.process.admin.page.processUnitInstanceList.queryByTimeTip=Input unitCode, time range and other
easyflow.process.admin.page.processUnitInstanceList.onlyFirstPageSupport=Only support first page
easyflow.process.admin.page.processUnitInstanceList.queryProcessUnitCode=Unit code
easyflow.process.admin.page.processUnitInstanceList.querySelect=Select
easyflow.process.admin.page.processUnitInstanceList.queryBizNo=Biz no
easyflow.process.admin.page.processUnitInstanceList.queryInstanceNo=Instance no
easyflow.process.admin.page.processUnitInstanceList.queryCreatedDateStart=Created date start
easyflow.process.admin.page.processUnitInstanceList.queryCreatedDateEnd=Created date end
easyflow.process.admin.page.processUnitInstanceList.queryResult=Result
easyflow.process.admin.page.processUnitInstanceList.queryResultSuccess=Success
easyflow.process.admin.page.processUnitInstanceList.queryResultFail=Fail
easyflow.process.admin.page.processUnitInstanceList.queryResultDoing=Doing
easyflow.process.admin.page.processUnitInstanceList.queryResultException=Exception
easyflow.process.admin.page.processUnitInstanceList.queryBtn=Query
easyflow.process.admin.page.processUnitInstanceList.instanceList=Process unit instance list
easyflow.process.admin.page.processUnitInstanceList.dateFormatInvalid=Date format invalid
easyflow.process.admin.page.processUnitInstanceList.instanceInfoCannotNull=Instance no or unitCode+bizNo cannot null
easyflow.process.admin.page.processUnitInstanceList.processUnitCodeCannotNull=Process unit code cannot null
easyflow.process.admin.page.processUnitInstanceList.timeRangeCannotNull=Start time and end time cannot null
easyflow.process.admin.page.processUnitInstanceList.createdDateStartCannotGtEnd=Created date start cannot greater than end
easyflow.process.admin.page.processUnitInstanceList.TimeRangeCannotGt30Days=Time range cannot greater than 30 days
easyflow.process.admin.page.processUnitInstanceList.instanceNo=Instance no
easyflow.process.admin.page.processUnitInstanceList.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitInstanceList.bizNo=Biz no
easyflow.process.admin.page.processUnitInstanceList.productCode=Product code
easyflow.process.admin.page.processUnitInstanceList.result=Result
easyflow.process.admin.page.processUnitInstanceList.resultSuccess=Success
easyflow.process.admin.page.processUnitInstanceList.resultFail=Fail
easyflow.process.admin.page.processUnitInstanceList.resultDoing=Doing
easyflow.process.admin.page.processUnitInstanceList.resultException=Exception
easyflow.process.admin.page.processUnitInstanceList.requestContent=Request content
easyflow.process.admin.page.processUnitInstanceList.responseContent=Response content
easyflow.process.admin.page.processUnitInstanceList.autoRuntimes=Auto run times
easyflow.process.admin.page.processUnitInstanceList.autoRunFlag=Auto run flag
easyflow.process.admin.page.processUnitInstanceList.nextAutoRunTime=Next auto run time
easyflow.process.admin.page.processUnitInstanceList.vars=Variables
easyflow.process.admin.page.processUnitInstanceList.extData=Ext data
easyflow.process.admin.page.processUnitInstanceList.createdDate=Created date
easyflow.process.admin.page.processUnitInstanceList.modifiedDate=Modified date
easyflow.process.admin.page.processUnitInstanceList.nextPage=Next page









