easyflow.process.admin.page.processUnitExecutionDetail.executionDetailInfo=Execution details
easyflow.process.admin.page.processUnitExecutionDetail.executionNo=Execution No.
easyflow.process.admin.page.processUnitExecutionDetail.requestNo=Request No.
easyflow.process.admin.page.processUnitExecutionDetail.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionDetail.bizNo=Business No.
easyflow.process.admin.page.processUnitExecutionDetail.productCode=Product code
easyflow.process.admin.page.processUnitExecutionDetail.result=Result
easyflow.process.admin.page.processUnitExecutionDetail.resultSuccess=Success
easyflow.process.admin.page.processUnitExecutionDetail.resultFailed=Failed
easyflow.process.admin.page.processUnitExecutionDetail.resultIn progress=In progress
easyflow.process.admin.page.processUnitExecutionDetail.resultException=Exception
easyflow.process.admin.page.processUnitExecutionDetail.execType=Execution type
easyflow.process.admin.page.processUnitExecutionDetail.execTypeSync=Sync
easyflow.process.admin.page.processUnitExecutionDetail.execTypeManual=Manual
easyflow.process.admin.page.processUnitExecutionDetail.execTypeTask=Task
easyflow.process.admin.page.processUnitExecutionDetail.execTypeMsg=Message
easyflow.process.admin.page.processUnitExecutionDetail.elaspeTime=Elapsed time
easyflow.process.admin.page.processUnitExecutionDetail.requestTime=Request time
easyflow.process.admin.page.processUnitExecutionDetail.responseTime=Response time
easyflow.process.admin.page.processUnitExecutionDetail.createdDate=Created date
easyflow.process.admin.page.processUnitExecutionDetail.modifiedDate=Modified date
easyflow.process.admin.page.processUnitExecutionDetail.requestContent=Request content
easyflow.process.admin.page.processUnitExecutionDetail.responseContent=Response content
easyflow.process.admin.page.processUnitExecutionDetail.extData=Extended data

easyflow.process.admin.page.processUnitInstanceDetail.instanceDetailInfo=Instance details
easyflow.process.admin.page.processUnitInstanceDetail.instanceNo=Instance No.
easyflow.process.admin.page.processUnitInstanceDetail.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitInstanceDetail.bizNo=Business No.
easyflow.process.admin.page.processUnitInstanceDetail.productCode=Product code
easyflow.process.admin.page.processUnitInstanceDetail.result=Result
easyflow.process.admin.page.processUnitInstanceDetail.resultSuccess=Success
easyflow.process.admin.page.processUnitInstanceDetail.resultFailed=Failed
easyflow.process.admin.page.processUnitInstanceDetail.resultIn progress=In progress
easyflow.process.admin.page.processUnitInstanceDetail.resultException=Exception
easyflow.process.admin.page.processUnitInstanceDetail.autoRunTimes=Auto-run count
easyflow.process.admin.page.processUnitInstanceDetail.autoRunFlag=Auto-run flag
easyflow.process.admin.page.processUnitInstanceDetail.nextAutoRunTime=Next auto-run time
easyflow.process.admin.page.processUnitInstanceDetail.createdDate=Created date
easyflow.process.admin.page.processUnitInstanceDetail.modifiedDate=Modified date
easyflow.process.admin.page.processUnitInstanceDetail.requestContent=Request content
easyflow.process.admin.page.processUnitInstanceDetail.responseContent=Response content
easyflow.process.admin.page.processUnitInstanceDetail.vars=Variables
easyflow.process.admin.page.processUnitInstanceDetail.extData=Extended data
easyflow.process.admin.page.processUnitInstanceDetail.instanceShardInfo=Instance shard info
easyflow.process.admin.page.processUnitInstanceDetail.shard=Shard
easyflow.process.admin.page.processUnitInstanceDetail.db=DB
easyflow.process.admin.page.processUnitInstanceDetail.table=Table 
easyflow.process.admin.page.processUnitInstanceDetail.slaveShard=Slave shard
easyflow.process.admin.page.processUnitInstanceDetail.slaveDB=Slave db
easyflow.process.admin.page.processUnitInstanceDetail.slaveTable=Slave table
easyflow.process.admin.page.processUnitInstanceDetail.executionNo=Execution No.
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestNo=Request No.
easyflow.process.admin.page.processUnitInstanceDetail.executionResult=Result
easyflow.process.admin.page.processUnitInstanceDetail.executionResultSuccess=Success
easyflow.process.admin.page.processUnitInstanceDetail.executionResultFailed=Failed
easyflow.process.admin.page.processUnitInstanceDetail.executionResultIn progress=In progress
easyflow.process.admin.page.processUnitInstanceDetail.executionResultException=Exception
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestContent=Request content
easyflow.process.admin.page.processUnitInstanceDetail.executionResponseContent=Response content
easyflow.process.admin.page.processUnitInstanceDetail.executionExecType=Execution type
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeSync=Sync
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeManual=Manual
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeTask=Task
easyflow.process.admin.page.processUnitInstanceDetail.executionExecTypeMsg=Message
easyflow.process.admin.page.processUnitInstanceDetail.executionRequestTime=Request time
easyflow.process.admin.page.processUnitInstanceDetail.executionResponseTime=Response time
easyflow.process.admin.page.processUnitInstanceDetail.executionElapseTime=Elapsed time
easyflow.process.admin.page.processUnitInstanceDetail.executionExtData=Extended data


easyflow.process.admin.page.processUnitExecutionList.executionManagement=Execution management
easyflow.process.admin.page.processUnitExecutionList.queryType=Query type
easyflow.process.admin.page.processUnitExecutionList.queryByInstance=Query by instance
easyflow.process.admin.page.processUnitExecutionList.queryByInstanceTip=Enter instance No. or unitCode + bizNo
easyflow.process.admin.page.processUnitExecutionList.queryByTime=Query by time range
easyflow.process.admin.page.processUnitExecutionList.queryByTimeTip=Enter unitCode, time range, and other criteria
easyflow.process.admin.page.processUnitExecutionList.onlyFirstPageSupport=Only the first page is supported
easyflow.process.admin.page.processUnitExecutionList.queryProcessUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionList.querySelect=Select
easyflow.process.admin.page.processUnitExecutionList.queryBizNo=Business No.
easyflow.process.admin.page.processUnitExecutionList.queryInstanceNo=Instance No.
easyflow.process.admin.page.processUnitExecutionList.queryResult=Result
easyflow.process.admin.page.processUnitExecutionList.queryResultSuccess=Success
easyflow.process.admin.page.processUnitExecutionList.queryResultFailed=Failed
easyflow.process.admin.page.processUnitExecutionList.queryResultIn progress=In progress
easyflow.process.admin.page.processUnitExecutionList.queryResultException=Exception
easyflow.process.admin.page.processUnitExecutionList.queryRequestTimeStart=Request time start
easyflow.process.admin.page.processUnitExecutionList.queryRequestTimeEnd=Request time end
easyflow.process.admin.page.processUnitExecutionList.queryElapseTimeStart=Elapsed time start
easyflow.process.admin.page.processUnitExecutionList.queryElapseTimeEnd=Elapsed time end
easyflow.process.admin.page.processUnitExecutionList.queryBtn=Query
easyflow.process.admin.page.processUnitExecutionList.executionList=Execution list
easyflow.process.admin.page.processUnitExecutionList.dateFormatInvalid=Date format invalid
easyflow.process.admin.page.processUnitExecutionList.instanceInfoCannotNull=Instance No. or unitCode + bizNo cannot be empty
easyflow.process.admin.page.processUnitExecutionList.processUnitCodeCannotNull=Process unit code cannot be empty
easyflow.process.admin.page.processUnitExecutionList.timeRangeCannotNull=Start time and end time cannot be empty
easyflow.process.admin.page.processUnitExecutionList.startTimeCannotGtEndTime=Start time cannot be later than end time
easyflow.process.admin.page.processUnitExecutionList.TimeRangeCannotGt30Days=Time range cannot exceed 30 days
easyflow.process.admin.page.processUnitExecutionList.executionNo=Execution No.
easyflow.process.admin.page.processUnitExecutionList.requestNo=Request No.
easyflow.process.admin.page.processUnitExecutionList.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitExecutionList.bizNo=Business No.
easyflow.process.admin.page.processUnitExecutionList.result=Result
easyflow.process.admin.page.processUnitExecutionList.resultSuccess=Success
easyflow.process.admin.page.processUnitExecutionList.resultFailed=Failed
easyflow.process.admin.page.processUnitExecutionList.resultIn progress=In progress
easyflow.process.admin.page.processUnitExecutionList.resultException=Exception
easyflow.process.admin.page.processUnitExecutionList.requestContent=Request content
easyflow.process.admin.page.processUnitExecutionList.responseContent=Response content
easyflow.process.admin.page.processUnitExecutionList.execType=Execution type
easyflow.process.admin.page.processUnitExecutionList.requestTime=Request time
easyflow.process.admin.page.processUnitExecutionList.responseTime=Response time
easyflow.process.admin.page.processUnitExecutionList.elaspeTime=Elapsed time
easyflow.process.admin.page.processUnitExecutionList.extData=Extended data
easyflow.process.admin.page.processUnitExecutionList.createdDate=Created date
easyflow.process.admin.page.processUnitExecutionList.modifiedDate=Modified date
easyflow.process.admin.page.processUnitExecutionList.nextPage=Next page

easyflow.process.admin.page.processUnitInstanceList.instanceManagement=Instance management
easyflow.process.admin.page.processUnitInstanceList.queryByInstance=Query by instance
easyflow.process.admin.page.processUnitInstanceList.queryByInstanceTip=Input instanceNo or bizNo+unitCode
easyflow.process.admin.page.processUnitInstanceList.queryByTime=Query by time range
easyflow.process.admin.page.processUnitInstanceList.queryByTimeTip=Enter unitCode, time range, and other criteria
easyflow.process.admin.page.processUnitInstanceList.onlyFirstPageSupport=Only the first page is supported
easyflow.process.admin.page.processUnitInstanceList.queryProcessUnitCode=Unit code
easyflow.process.admin.page.processUnitInstanceList.querySelect=Select
easyflow.process.admin.page.processUnitInstanceList.queryBizNo=Business No.
easyflow.process.admin.page.processUnitInstanceList.queryInstanceNo=Instance No.
easyflow.process.admin.page.processUnitInstanceList.queryCreatedDateStart=Created date start
easyflow.process.admin.page.processUnitInstanceList.queryCreatedDateEnd=Created date end
easyflow.process.admin.page.processUnitInstanceList.queryResult=Result
easyflow.process.admin.page.processUnitInstanceList.queryResultSuccess=Success
easyflow.process.admin.page.processUnitInstanceList.queryResultFailed=Failed
easyflow.process.admin.page.processUnitInstanceList.queryResultIn progress=In progress
easyflow.process.admin.page.processUnitInstanceList.queryResultException=Exception
easyflow.process.admin.page.processUnitInstanceList.queryBtn=Query
easyflow.process.admin.page.processUnitInstanceList.instanceList=Process unit instance list
easyflow.process.admin.page.processUnitInstanceList.dateFormatInvalid=Date format invalid
easyflow.process.admin.page.processUnitInstanceList.instanceInfoCannotNull=Instance No. or unitCode + bizNo cannot be empty
easyflow.process.admin.page.processUnitInstanceList.processUnitCodeCannotNull=Process unit code cannot be empty
easyflow.process.admin.page.processUnitInstanceList.timeRangeCannotNull=Start time and end time cannot be empty
easyflow.process.admin.page.processUnitInstanceList.createdDateStartCannotGtEnd=Created date start cannot be later than end
easyflow.process.admin.page.processUnitInstanceList.TimeRangeCannotGt30Days=Time range cannot exceed 30 days
easyflow.process.admin.page.processUnitInstanceList.instanceNo=Instance No.
easyflow.process.admin.page.processUnitInstanceList.processUnitCode=Process unit code
easyflow.process.admin.page.processUnitInstanceList.bizNo=Business No.
easyflow.process.admin.page.processUnitInstanceList.productCode=Product code
easyflow.process.admin.page.processUnitInstanceList.result=Result
easyflow.process.admin.page.processUnitInstanceList.resultSuccess=Success
easyflow.process.admin.page.processUnitInstanceList.resultFailed=Failed
easyflow.process.admin.page.processUnitInstanceList.resultIn progress=In progress
easyflow.process.admin.page.processUnitInstanceList.resultException=Exception
easyflow.process.admin.page.processUnitInstanceList.requestContent=Request content
easyflow.process.admin.page.processUnitInstanceList.responseContent=Response content
easyflow.process.admin.page.processUnitInstanceList.autoRuntimes=Auto-run count
easyflow.process.admin.page.processUnitInstanceList.autoRunFlag=Auto-run flag
easyflow.process.admin.page.processUnitInstanceList.nextAutoRunTime=Next auto-run time
easyflow.process.admin.page.processUnitInstanceList.vars=Variables
easyflow.process.admin.page.processUnitInstanceList.extData=Extended data
easyflow.process.admin.page.processUnitInstanceList.createdDate=Created date
easyflow.process.admin.page.processUnitInstanceList.modifiedDate=Modified date
easyflow.process.admin.page.processUnitInstanceList.nextPage=Next page









