easyflow.process.server.tip.processDefinitionExists=Process definition already exists
easyflow.process.server.tip.processDefinitionNotExists=Process definition does not exist
easyflow.process.server.tip.processInstanceExists=Process instance already exists
easyflow.process.server.tip.processDefinitionNotExistsWithId=Process definition {0} does not exist
easyflow.process.server.tip.attachedProcessDefinitionCannotUpdate=The attached process cannot be updated. Please update the main process {0}.
easyflow.process.server.tip.matchedDefinitionNotFound=No matching definition found
easyflow.process.server.tip.latestDefinitionNotFound=Latest definition not found
easyflow.process.server.tip.taskExecuteUserAndWithdrawUserInconsistent=Task executor {0} is inconsistent with withdraw user {1}
easyflow.process.server.tip.cannotWithdrawForTaskNotEnd=The task has not ended and cannot be withdrawn
easyflow.process.server.tip.cannotWithdrawForInstanceClose=The process instance is closed and cannot be withdrawn
easyflow.process.server.tip.cannotWithdrawForNoConfig=Withdraw settings are not configured for node {0}
easyflow.process.server.tip.cannotWithdrawForPostNodeClose=Post node {0} is closed and cannot be withdrawn
easyflow.process.server.tip.cannotWithdrawForMultiplePreNodes=Node {0} has multiple previous nodes and cannot be withdrawn
easyflow.process.server.tip.cannotWithdrawForTaskProcessed=Post task {0} has been processed and cannot be withdrawn
easyflow.process.server.tip.cannotWithdrawForReason=The task cannot be withdrawn. taskNo:{0}, reason:{1}
easyflow.process.server.tip.cannotCancelForReason=The process instance cannot be canceled. instanceNo:{0}, reason:{1}
easyflow.process.server.tip.cannotCancelForInstanceNotExists=Process instance not found
easyflow.process.server.tip.cannotCancelForCancelStatus=The process instance has already been canceled
easyflow.process.server.tip.cannotCancelForNotConfigCancel=The cancel flag is not configured in the definition
easyflow.process.server.tip.cannotCancelForUserInconsistent=The creator and canceling user are different, so the process cannot be canceled
easyflow.process.server.tip.cannotCancelForInstanceFinish=This process instance has finished and cannot be canceled
easyflow.process.server.tip.processIdInconsistent=Process definition ID is inconsistent
